// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: callback-service.proto

package org.apache.eventmesh.connector.openfunction.client;

public final class EventMeshGrpcService {

    private EventMeshGrpcService() {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
        com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
            (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
        descriptor;

    static {
        String[] descriptorData = {
            "\n\026callback-service.proto\022#org.apache.eve" +
                "ntmesh.cloudevents.v1\032\033eventmesh-cloudev" +
                "ents.proto\032\031google/protobuf/any.proto\032\037g" +
                "oogle/protobuf/timestamp.proto2\203\001\n\017Callb" +
                "ackService\022p\n\014OnTopicEvent\022/.org.apache." +
                "eventmesh.cloudevents.v1.CloudEvent\032/.or" +
                "g.apache.eventmesh.cloudevents.v1.CloudE" +
                "ventBA\n)org.apache.eventmesh.connect.ope" +
                "nfunctionB\024EventMeshGrpcServiceb\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
            new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                public com.google.protobuf.ExtensionRegistry assignDescriptors(
                    com.google.protobuf.Descriptors.FileDescriptor root) {
                    descriptor = root;
                    return null;
                }
            };
        com.google.protobuf.Descriptors.FileDescriptor
            .internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {
                    org.apache.eventmesh.common.protocol.grpc.cloudevents.EventMeshCloudEvents.getDescriptor(),
                    com.google.protobuf.AnyProto.getDescriptor(),
                    com.google.protobuf.TimestampProto.getDescriptor(),
                }, assigner);
        org.apache.eventmesh.common.protocol.grpc.cloudevents.EventMeshCloudEvents.getDescriptor();
        com.google.protobuf.AnyProto.getDescriptor();
        com.google.protobuf.TimestampProto.getDescriptor();
    }

    // @@protoc_insertion_point(outer_class_scope)
}
