#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

github:
  description: EventMesh is a new generation serverless event middleware for building distributed event-driven applications.
  homepage: https://eventmesh.apache.org/
  labels:
    - pubsub
    - event-mesh
    - event-gateway
    - event-driven
    - event-streaming
    - event-sourcing
    - event-governance
    - event-connector
    - cloud-native
    - serverless
    - serverless-workflow
    - esb
    - message-bus
    - cqrs
    - multi-runtime
    - microservice
    - hacktoberfest
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: false
  protected_branches:
    master:
      required_status_checks:
        strict: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 2
  # Attempt to make the auto-generated github emails more easily readable in email clients.
  custom_subjects:
    new_pr: "[PR] {title} ({repository})"
    close_pr: "Re: [PR] {title} ({repository})"
    comment_pr: "Re: [PR] {title} ({repository})"
    diffcomment: "Re: [PR] {title} ({repository})"
    merge_pr: "Re: [PR] {title} ({repository})"
    new_issue: "[I] {title} ({repository})"
    comment_issue: "Re: [I] {title} ({repository})"
    close_issue: "Re: [I] {title} ({repository})"
    catchall: "[GH] {title} ({repository})"
    new_discussion: "[D] {title} ({repository})"
    edit_discussion: "Re: [D] {title} ({repository})"
    close_discussion: "Re: [D] {title} ({repository})"
    close_discussion_with_comment: "Re: [D] {title} ({repository})"
    reopen_discussion: "Re: [D] {title} ({repository})"
    new_comment_discussion: "Re: [D] {title} ({repository})"
    edit_comment_discussion: "Re: [D] {title} ({repository})"
    delete_comment_discussion: "Re: [D] {title} ({repository})"
notifications:
    commits: commits@eventmesh.apache.org
    # Send all issue emails (new, closed, comments) to issues@
    issues: issues@eventmesh.apache.org
    # Send new/closed PR notifications to dev@
    pullrequests_status: dev@eventmesh.apache.org
    # Send individual PR comments/reviews to issues@
    pullrequests_comment: issues@eventmesh.apache.org
    jira_options: link label worklog
