// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.apache.eventmesh.common.protocol.catalog.protos;

@SuppressWarnings({"all"})
public interface QueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventmesh.catalog.api.protocol.QueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string operation_id = 1;</code>
   * @return The operationId.
   */
  String getOperationId();
  /**
   * <code>string operation_id = 1;</code>
   * @return The bytes for operationId.
   */
  com.google.protobuf.ByteString
      getOperationIdBytes();
}
