// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog.proto

package org.apache.eventmesh.common.protocol.catalog.protos;

@SuppressWarnings({"all"})
public interface RegistryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventmesh.catalog.api.protocol.RegistryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string file_name = 1;</code>
   * @return The fileName.
   */
  String getFileName();
  /**
   * <code>string file_name = 1;</code>
   * @return The bytes for fileName.
   */
  com.google.protobuf.ByteString
      getFileNameBytes();

  /**
   * <code>string definition = 2;</code>
   * @return The definition.
   */
  String getDefinition();
  /**
   * <code>string definition = 2;</code>
   * @return The bytes for definition.
   */
  com.google.protobuf.ByteString
      getDefinitionBytes();
}
