spring:
  h2:
    console:
      path: /h2-console #进入h2 web操作界面的路径
      enabled: true #开启h2 web界面
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:[path/to/db]
    username: root
    password: test
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 13579