// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

//! HTTP producer.

use tracing::debug;

use crate::config::HttpClientConfig;
use crate::error::{EventMeshError, Result};
use crate::model::{EventMeshMessage, EventMeshProtocolType, PublishResponse};
use crate::transport::http::client::EventMeshHttpClient;
use crate::transport::http::codec::{self, uri};
use crate::transport::Publisher;

/// HTTP-based producer.
///
/// Implements publishing over the EventMesh HTTP protocol.
pub struct HttpProducer {
    client: EventMeshHttpClient,
}

impl HttpProducer {
    /// Create a producer from a config.
    pub fn new(config: HttpClientConfig) -> Result<Self> {
        let client = EventMeshHttpClient::new(config)?;
        Ok(Self { client })
    }

    /// Publish a native CloudEvent (JSON-serialized) behind the `cloud_events`
    /// feature. The CloudEvent's `subject` is used as the topic.
    #[cfg(feature = "cloud_events")]
    pub async fn publish_cloud_event(
        &self,
        mut event: cloudevents::Event,
    ) -> Result<PublishResponse> {
        use cloudevents::AttributesReader;

        // The runtime's CloudEvents HTTP resolver reads bizseqno/uniqueid from
        // CloudEvent extension attributes — NOT from the form fields generated by
        // encode_publish — and rejects the request with EVENTMESH_PROTOCOL_BODY_ERR
        // when either is missing. Populate them before serializing.
        ensure_ce_extension(&mut event, "bizseqno");
        ensure_ce_extension(&mut event, "uniqueid");
        ensure_ce_ttl(&mut event);

        let topic = event
            .subject()
            .ok_or_else(|| {
                EventMeshError::InvalidMessage("CloudEvent subject (topic) is required".into())
            })?
            .to_string();
        let json = serde_json::to_string(&event)?;
        let msg = EventMeshMessage::builder()
            .topic(topic)
            .content(json)
            .build()?;
        self.publish_with_protocol(msg, EventMeshProtocolType::CloudEvents)
            .await
    }

    /// Internal publish with a specific protocol type.
    async fn publish_with_protocol(
        &self,
        message: EventMeshMessage,
        protocol_type: EventMeshProtocolType,
    ) -> Result<PublishResponse> {
        message.validate_for_publish()?;
        let config = self.client.config();
        let body = codec::encode_publish(&message, &config.identity);
        let code = codec::publish_code();
        let headers = codec::build_headers(code, protocol_type, &config.identity);
        let timeout = config.timeout;
        let text = self
            .client
            .post_form(uri::ROOT, &body, &headers, timeout)
            .await?;
        let response = codec::parse_response(&text)?;
        if !response.is_success() {
            return Err(EventMeshError::Server {
                code: response.code.unwrap_or(-1) as i32,
                message: response.message.unwrap_or_else(|| "publish failed".into()),
            });
        }
        debug!("published topic={:?}", message.topic);
        Ok(response)
    }
}

impl Publisher for HttpProducer {
    async fn publish(&self, message: EventMeshMessage) -> Result<PublishResponse> {
        self.publish_with_protocol(message, EventMeshProtocolType::EventMeshMessage)
            .await
    }

    async fn publish_batch(&self, _messages: Vec<EventMeshMessage>) -> Result<PublishResponse> {
        // The runtime's HTTP batch path (request code 102) expects a legacy
        // `batchId`/`size`/`contents`/`producerGroup` body that is routed
        // through `ProtocolAdaptor.toBatchCloudEvent`, which does not accept
        // `HttpCommand` inputs — only the gRPC `BatchEventMeshCloudEventWrapper`.
        // Until a supported HTTP batch format is available, this operation is
        // not exposed.
        Err(EventMeshError::Unsupported(
            "batch publish is not supported over the HTTP transport; use individual publish calls or the gRPC transport"
                .into(),
        ))
    }
}

/// Ensure a CloudEvent extension attribute is present and non-blank,
/// generating a random 30-digit numeric value if the caller did not supply one.
///
/// The runtime's CloudEvents HTTP resolver does not bridge `bizseqno` or
/// `uniqueid` from the request form fields into CloudEvent extensions (only
/// `producergroup` is bridged), so they must be embedded inside the JSON
/// content before serialization.
#[cfg(feature = "cloud_events")]
fn ensure_ce_extension(event: &mut cloudevents::Event, key: &str) {
    use crate::common::util::RandomStringUtils;

    let missing = match event.extension(key) {
        None => true,
        Some(v) => v.to_string().trim().is_empty(),
    };
    if missing {
        event.set_extension(key, RandomStringUtils::generate_num(30));
    }
}

/// Ensure a CloudEvent contains the TTL extension required by the HTTP sync
/// request processor. Unlike the form field emitted by `encode_publish`, the
/// CloudEvents resolver reads TTL only from the serialized event.
#[cfg(feature = "cloud_events")]
fn ensure_ce_ttl(event: &mut cloudevents::Event) {
    use crate::common::DEFAULT_MESSAGE_TTL;

    let missing = match event.extension("ttl") {
        None => true,
        Some(value) => value.to_string().trim().is_empty(),
    };
    if missing {
        event.set_extension("ttl", DEFAULT_MESSAGE_TTL.to_string());
    }
}

#[cfg(all(test, feature = "cloud_events"))]
mod tests {
    use super::*;

    fn make_event() -> cloudevents::Event {
        use cloudevents::{EventBuilder, EventBuilderV10};
        EventBuilderV10::new()
            .id("test-id")
            .source("urn:test")
            .ty("test-type")
            .subject("test-topic")
            .data("text/plain", "hello")
            .build()
            .unwrap()
    }

    #[test]
    fn ensure_ce_extension_generates_when_missing() {
        let mut event = make_event();
        assert!(event.extension("bizseqno").is_none());
        ensure_ce_extension(&mut event, "bizseqno");
        let v = event
            .extension("bizseqno")
            .expect("extension should be set");
        let s = v.to_string();
        assert!(!s.is_empty());
        assert!(s.chars().all(|c| c.is_ascii_digit()));
    }

    #[test]
    fn ensure_ce_extension_preserves_existing_value() {
        let mut event = make_event();
        event.set_extension("bizseqno", "caller-supplied-seq".to_string());
        ensure_ce_extension(&mut event, "bizseqno");
        assert_eq!(
            event.extension("bizseqno").unwrap().to_string(),
            "caller-supplied-seq"
        );
    }

    #[test]
    fn ensure_ce_extension_overwrites_blank_value() {
        let mut event = make_event();
        event.set_extension("uniqueid", "".to_string());
        ensure_ce_extension(&mut event, "uniqueid");
        let v = event.extension("uniqueid").unwrap().to_string();
        assert!(!v.is_empty());
    }

    #[test]
    fn ensure_ce_ttl_defaults_when_missing_and_preserves_caller_value() {
        let mut event = make_event();
        ensure_ce_ttl(&mut event);
        assert_eq!(
            event.extension("ttl").unwrap().to_string(),
            crate::common::DEFAULT_MESSAGE_TTL.to_string()
        );

        event.set_extension("ttl", "9000".to_string());
        ensure_ce_ttl(&mut event);
        assert_eq!(event.extension("ttl").unwrap().to_string(), "9000");
    }

    #[test]
    fn publish_cloud_event_serializes_extensions() {
        // Verify that after ensure_ce_extension runs, the serialized JSON
        // contains the extension attributes — this is what the runtime reads.
        let mut event = make_event();
        ensure_ce_extension(&mut event, "bizseqno");
        ensure_ce_extension(&mut event, "uniqueid");
        ensure_ce_ttl(&mut event);
        let json = serde_json::to_string(&event).unwrap();
        assert!(
            json.contains("bizseqno"),
            "serialized CloudEvent must contain bizseqno extension: {json}"
        );
        assert!(
            json.contains("uniqueid"),
            "serialized CloudEvent must contain uniqueid extension: {json}"
        );
        assert!(
            json.contains("\"ttl\":\"4000\""),
            "serialized CloudEvent must contain ttl extension: {json}"
        );
    }
}
