dependencies {
    implementation project(":eventmesh-connector-runtime")
    implementation 'io.cloudevents:cloudevents-core'
    implementation 'org.slf4j:slf4j-api'
    implementation 'software.amazon.awssdk:s3:2.25.16'
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
