#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

pubSubConfig:
  meshAddress: 127.0.0.1:10000
  subject: TopicTest
  idc: FT
  env: PRD
  group: httpSink
  appId: 5032
  userName: httpSinkUser
  passWord: httpPassWord
connectorConfig:
  connectorName: httpSink
  urls:
   - http://127.0.0.1:8987/test
  keepAlive: true
  keepAliveTimeout: 60000
  idleTimeout: 5000   # timeunit: ms, recommended scope: common(5s - 10s), webhook(15s - 60s)
  connectionTimeout: 5000   # timeunit: ms, recommended scope: 5 - 10s
  maxConnectionPoolSize: 5
  retryConfig:
    maxRetries: 2
    interval: 1000
    retryOnNonSuccess: false
  webhookConfig:
    activate: false
    exportPath: /export
    port: 8988
    serverIdleTimeout: 5000
    maxStorageSize: 5000
