/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventmesh-cloudevents.proto

package org.apache.eventmesh.common.protocol.grpc.cloudevents;

public final class EventMeshCloudEvents {
  private EventMeshCloudEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_AttributesEntry_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_CloudEventAttributeValue_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_CloudEventAttributeValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEventBatch_descriptor;
  static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_apache_eventmesh_cloudevents_v1_CloudEventBatch_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033eventmesh-cloudevents.proto\022#org.apach" +
      "e.eventmesh.cloudevents.v1\032\031google/proto" +
      "buf/any.proto\032\037google/protobuf/timestamp" +
      ".proto\"\324\004\n\nCloudEvent\022\n\n\002id\030\001 \001(\t\022\016\n\006sou" +
      "rce\030\002 \001(\t\022\024\n\014spec_version\030\003 \001(\t\022\014\n\004type\030" +
      "\004 \001(\t\022S\n\nattributes\030\005 \003(\0132?.org.apache.e" +
      "ventmesh.cloudevents.v1.CloudEvent.Attri" +
      "butesEntry\022\025\n\013binary_data\030\006 \001(\014H\000\022\023\n\ttex" +
      "t_data\030\007 \001(\tH\000\022*\n\nproto_data\030\010 \001(\0132\024.goo" +
      "gle.protobuf.AnyH\000\032{\n\017AttributesEntry\022\013\n" +
      "\003key\030\001 \001(\t\022W\n\005value\030\002 \001(\0132H.org.apache.e" +
      "ventmesh.cloudevents.v1.CloudEvent.Cloud" +
      "EventAttributeValue:\0028\001\032\323\001\n\030CloudEventAt" +
      "tributeValue\022\024\n\nce_boolean\030\001 \001(\010H\000\022\024\n\nce" +
      "_integer\030\002 \001(\005H\000\022\023\n\tce_string\030\003 \001(\tH\000\022\022\n" +
      "\010ce_bytes\030\004 \001(\014H\000\022\020\n\006ce_uri\030\005 \001(\tH\000\022\024\n\nc" +
      "e_uri_ref\030\006 \001(\tH\000\0222\n\014ce_timestamp\030\007 \001(\0132" +
      "\032.google.protobuf.TimestampH\000B\006\n\004attrB\006\n" +
      "\004data\"R\n\017CloudEventBatch\022?\n\006events\030\001 \003(\013" +
      "2/.org.apache.eventmesh.cloudevents.v1.C" +
      "loudEventBO\n5org.apache.eventmesh.common" +
      ".protocol.grpc.cloudeventsB\024EventMeshClo" +
      "udEventsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_descriptor,
        new String[] { "Id", "Source", "SpecVersion", "Type", "Attributes", "BinaryData", "TextData", "ProtoData", "Data", });
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_AttributesEntry_descriptor =
      internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_descriptor.getNestedTypes().get(0);
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_AttributesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_CloudEventAttributeValue_descriptor =
      internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_descriptor.getNestedTypes().get(1);
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_CloudEventAttributeValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_eventmesh_cloudevents_v1_CloudEvent_CloudEventAttributeValue_descriptor,
        new String[] { "CeBoolean", "CeInteger", "CeString", "CeBytes", "CeUri", "CeUriRef", "CeTimestamp", "Attr", });
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEventBatch_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_apache_eventmesh_cloudevents_v1_CloudEventBatch_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_apache_eventmesh_cloudevents_v1_CloudEventBatch_descriptor,
        new String[] { "Events", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
