#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
<<<<<<< HEAD:eventmesh-serverless-workflow/configs/controller.yaml

=======
#

<<<<<<<< HEAD:eventmesh-connector-plugin/eventmesh-connector-pulsar/src/test/resources/pulsar-client.properties
eventMesh.server.pulsar.service=127.0.0.1:6650
eventMesh.server.pulsar.authPlugin=authPlugin-success!!!
eventMesh.server.pulsar.authParams=authParams-success!!!
========
>>>>>>> 110f7ce9 (add workflow controller module):eventmesh-workflow-go/configs/controller.yaml
server:
  port: 11022
plugins:
  database:
    mysql:
      dsn: "root:123456@(127.0.0.1:3306)/db_workflow?charset=utf8&parseTime=True&loc=Local"
      max_idle: 50
      max_open: 100
      max_lifetime: 180000
  log:
    default:
      - writer: file
        level: info
        writer_config:
          filename: ./workflow.log
          max_size: 10
          max_backups: 10
          max_age: 7
<<<<<<< HEAD:eventmesh-serverless-workflow/configs/controller.yaml
          compress:  false
=======
          compress:  false
>>>>>>>> 110f7ce9 (add workflow controller module):eventmesh-serverless-workflow/configs/controller.yaml
>>>>>>> 110f7ce9 (add workflow controller module):eventmesh-workflow-go/configs/controller.yaml
