#!/bin/bash
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# ********************************************************************
# This script used to check the dependencies are all in our exception.
# This will not check the license legality
# ********************************************************************

# Used to store the tmp files
decompress_conf='build/tmp'
# store all our known dependencies
known_third_party_dependencies_txt='tools/dependency-check/known-dependencies.txt'

# Below files is generated by this script
# store all dependencies from EventMesh binary jar
all_dependencies_txt='tools/dependency-check/all-dependencies.txt'
# store all EventMesh self modules' name
self_modules_txt='tools/dependency-check/self-modules.txt'
# store all third party dependencies
third_party_dependencies_txt='tools/dependency-check/third-party-dependencies.txt'

mkdir -p $decompress_conf
tar -zxf build/eventmesh*.tar.gz -C $decompress_conf

./gradlew printProjects | grep '.jar' > "$self_modules_txt"

find "$decompress_conf" -name "*.jar" -exec basename {} \; | sort | uniq > "$all_dependencies_txt"

grep -wvf "$self_modules_txt" "$all_dependencies_txt" | sort | uniq > "$third_party_dependencies_txt"

# Only keep the artifact name
sed -i 's/-[0-9].*\.jar//g' "$third_party_dependencies_txt"

# If the check is success it will return 0
sort "$known_third_party_dependencies_txt" | diff - "$third_party_dependencies_txt"

compareCode=$?
if [ $compareCode -eq 0 ]
then
  echo "Dependency check success"
else
  echo "Dependency check failed. Please check if you add known dependencies"
  exit $compareCode
fi