dependencies {
    implementation project(":eventmesh-connector-runtime")
    implementation 'io.cloudevents:cloudevents-core'
    implementation 'org.slf4j:slf4j-api'
    implementation "org.apache.rocketmq:rocketmq-client:4.9.8"
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
}
