# permissions for end users to edit eventmeshoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eventmeshoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eventmesh-operator
    app.kubernetes.io/part-of: eventmesh-operator
    app.kubernetes.io/managed-by: kustomize
  name: eventmeshoperator-editor-role
rules:
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - eventmeshoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - eventmeshoperators/status
  verbs:
  - get
