---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - connectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - connectors/finalizers
  verbs:
  - update
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - connectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - runtime
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - runtime/finalizers
  verbs:
  - update
- apiGroups:
  - eventmesh-operator.eventmesh
  resources:
  - runtime/status
  verbs:
  - get
  - patch
  - update
