// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventmesh-client.proto

package org.apache.eventmesh.common.protocol.grpc.protos;

public final class EventmeshGrpc {
  private EventmeshGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_RequestHeader_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_RequestHeader_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_BatchMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_PropertiesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_PropertiesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_Response_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_Subscription_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_Subscription_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_Subscription_SubscriptionItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_Subscription_SubscriptionItem_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_Heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_Heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_eventmesh_common_protocol_grpc_Heartbeat_HeartbeatItem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_eventmesh_common_protocol_grpc_Heartbeat_HeartbeatItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\026eventmesh-client.proto\022\036eventmesh.comm" +
      "on.protocol.grpc\"\332\001\n\rRequestHeader\022\013\n\003en" +
      "v\030\001 \001(\t\022\016\n\006region\030\002 \001(\t\022\013\n\003idc\030\003 \001(\t\022\n\n\002" +
      "ip\030\004 \001(\t\022\013\n\003pid\030\005 \001(\t\022\013\n\003sys\030\006 \001(\t\022\020\n\010us" +
      "ername\030\007 \001(\t\022\020\n\010password\030\010 \001(\t\022\020\n\010langua" +
      "ge\030\t \001(\t\022\024\n\014protocolType\030\n \001(\t\022\027\n\017protoc" +
      "olVersion\030\013 \001(\t\022\024\n\014protocolDesc\030\014 \001(\t\"\315\002" +
      "\n\020EventMeshMessage\022=\n\006header\030\001 \001(\0132-.eve" +
      "ntmesh.common.protocol.grpc.RequestHeade" +
      "r\022\025\n\rproducerGroup\030\002 \001(\t\022\r\n\005topic\030\003 \001(\t\022" +
      "\017\n\007content\030\004 \001(\t\022\013\n\003ttl\030\005 \001(\t\022\020\n\010uniqueI" +
      "d\030\006 \001(\t\022\016\n\006seqNum\030\007 \001(\t\022\013\n\003tag\030\010 \001(\t\022T\n\n" +
      "properties\030\t \003(\0132@.eventmesh.common.prot" +
      "ocol.grpc.EventMeshMessage.PropertiesEnt" +
      "ry\0321\n\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va" +
      "lue\030\002 \001(\t:\0028\001\"\260\003\n\014BatchMessage\022=\n\006header" +
      "\030\001 \001(\0132-.eventmesh.common.protocol.grpc." +
      "RequestHeader\022\025\n\rproducerGroup\030\002 \001(\t\022\r\n\005" +
      "topic\030\003 \001(\t\022M\n\013messageItem\030\004 \003(\01328.event" +
      "mesh.common.protocol.grpc.BatchMessage.M" +
      "essageItem\032\353\001\n\013MessageItem\022\017\n\007content\030\001 " +
      "\001(\t\022\013\n\003ttl\030\002 \001(\t\022\020\n\010uniqueId\030\003 \001(\t\022\016\n\006se" +
      "qNum\030\004 \001(\t\022\013\n\003tag\030\005 \001(\t\022\\\n\nproperties\030\006 " +
      "\003(\0132H.eventmesh.common.protocol.grpc.Bat" +
      "chMessage.MessageItem.PropertiesEntry\0321\n" +
      "\017PropertiesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"?\n\010Response\022\020\n\010respCode\030\001 \001(\t\022\017" +
      "\n\007respMsg\030\002 \001(\t\022\020\n\010respTime\030\003 \001(\t\"\212\004\n\014Su" +
      "bscription\022=\n\006header\030\001 \001(\0132-.eventmesh.c" +
      "ommon.protocol.grpc.RequestHeader\022\025\n\rcon" +
      "sumerGroup\030\002 \001(\t\022X\n\021subscriptionItems\030\003 " +
      "\003(\0132=.eventmesh.common.protocol.grpc.Sub" +
      "scription.SubscriptionItem\022\013\n\003url\030\004 \001(\t\032" +
      "\274\002\n\020SubscriptionItem\022\r\n\005topic\030\001 \001(\t\022\\\n\004m" +
      "ode\030\002 \001(\0162N.eventmesh.common.protocol.gr" +
      "pc.Subscription.SubscriptionItem.Subscri" +
      "ptionMode\022\\\n\004type\030\003 \001(\0162N.eventmesh.comm" +
      "on.protocol.grpc.Subscription.Subscripti" +
      "onItem.SubscriptionType\"4\n\020SubscriptionM" +
      "ode\022\016\n\nCLUSTERING\020\000\022\020\n\014BROADCASTING\020\001\"\'\n" +
      "\020SubscriptionType\022\t\n\005ASYNC\020\000\022\010\n\004SYNC\020\001\"\340" +
      "\002\n\tHeartbeat\022=\n\006header\030\001 \001(\0132-.eventmesh" +
      ".common.protocol.grpc.RequestHeader\022H\n\nc" +
      "lientType\030\002 \001(\01624.eventmesh.common.proto" +
      "col.grpc.Heartbeat.ClientType\022\025\n\rproduce" +
      "rGroup\030\003 \001(\t\022\025\n\rconsumerGroup\030\004 \001(\t\022O\n\016h" +
      "eartbeatItems\030\005 \003(\01327.eventmesh.common.p" +
      "rotocol.grpc.Heartbeat.HeartbeatItem\032+\n\r" +
      "HeartbeatItem\022\r\n\005topic\030\001 \001(\t\022\013\n\003url\030\002 \001(" +
      "\t\"\036\n\nClientType\022\007\n\003PUB\020\000\022\007\n\003SUB\020\0012\266\003\n\020Pu" +
      "blisherService\022e\n\007publish\0220.eventmesh.co" +
      "mmon.protocol.grpc.EventMeshMessage\032(.ev" +
      "entmesh.common.protocol.grpc.Response\022j\n" +
      "\014requestReply\0220.eventmesh.common.protoco" +
      "l.grpc.EventMeshMessage\032(.eventmesh.comm" +
      "on.protocol.grpc.Response\022f\n\014batchPublis" +
      "h\022,.eventmesh.common.protocol.grpc.Batch" +
      "Message\032(.eventmesh.common.protocol.grpc" +
      ".Response\022g\n\tbroadcast\0220.eventmesh.commo" +
      "n.protocol.grpc.EventMeshMessage\032(.event" +
      "mesh.common.protocol.grpc.Response2\322\002\n\017C" +
      "onsumerService\022c\n\tsubscribe\022,.eventmesh." +
      "common.protocol.grpc.Subscription\032(.even" +
      "tmesh.common.protocol.grpc.Response\022s\n\017s" +
      "ubscribeStream\022,.eventmesh.common.protoc" +
      "ol.grpc.Subscription\0320.eventmesh.common." +
      "protocol.grpc.EventMeshMessage0\001\022e\n\013unsu" +
      "bscribe\022,.eventmesh.common.protocol.grpc" +
      ".Subscription\032(.eventmesh.common.protoco" +
      "l.grpc.Response2t\n\020HeartbeatService\022`\n\th" +
      "eartbeat\022).eventmesh.common.protocol.grp" +
      "c.Heartbeat\032(.eventmesh.common.protocol." +
      "grpc.ResponseBC\n0org.apache.eventmesh.co" +
      "mmon.protocol.grpc.protosB\rEventmeshGrpc" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_eventmesh_common_protocol_grpc_RequestHeader_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_eventmesh_common_protocol_grpc_RequestHeader_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_RequestHeader_descriptor,
        new String[] { "Env", "Region", "Idc", "Ip", "Pid", "Sys", "Username", "Password", "Language", "ProtocolType", "ProtocolVersion", "ProtocolDesc", });
    internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_descriptor,
        new String[] { "Header", "ProducerGroup", "Topic", "Content", "Ttl", "UniqueId", "SeqNum", "Tag", "Properties", });
    internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_PropertiesEntry_descriptor =
      internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_descriptor.getNestedTypes().get(0);
    internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_EventMeshMessage_PropertiesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_BatchMessage_descriptor,
        new String[] { "Header", "ProducerGroup", "Topic", "MessageItem", });
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_descriptor =
      internal_static_eventmesh_common_protocol_grpc_BatchMessage_descriptor.getNestedTypes().get(0);
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_descriptor,
        new String[] { "Content", "Ttl", "UniqueId", "SeqNum", "Tag", "Properties", });
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_PropertiesEntry_descriptor =
      internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_descriptor.getNestedTypes().get(0);
    internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_PropertiesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_BatchMessage_MessageItem_PropertiesEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_eventmesh_common_protocol_grpc_Response_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_eventmesh_common_protocol_grpc_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_Response_descriptor,
        new String[] { "RespCode", "RespMsg", "RespTime", });
    internal_static_eventmesh_common_protocol_grpc_Subscription_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_eventmesh_common_protocol_grpc_Subscription_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_Subscription_descriptor,
        new String[] { "Header", "ConsumerGroup", "SubscriptionItems", "Url", });
    internal_static_eventmesh_common_protocol_grpc_Subscription_SubscriptionItem_descriptor =
      internal_static_eventmesh_common_protocol_grpc_Subscription_descriptor.getNestedTypes().get(0);
    internal_static_eventmesh_common_protocol_grpc_Subscription_SubscriptionItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_Subscription_SubscriptionItem_descriptor,
        new String[] { "Topic", "Mode", "Type", });
    internal_static_eventmesh_common_protocol_grpc_Heartbeat_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_eventmesh_common_protocol_grpc_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_Heartbeat_descriptor,
        new String[] { "Header", "ClientType", "ProducerGroup", "ConsumerGroup", "HeartbeatItems", });
    internal_static_eventmesh_common_protocol_grpc_Heartbeat_HeartbeatItem_descriptor =
      internal_static_eventmesh_common_protocol_grpc_Heartbeat_descriptor.getNestedTypes().get(0);
    internal_static_eventmesh_common_protocol_grpc_Heartbeat_HeartbeatItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_eventmesh_common_protocol_grpc_Heartbeat_HeartbeatItem_descriptor,
        new String[] { "Topic", "Url", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
