// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventmesh-client.proto

package org.apache.eventmesh.common.protocol.grpc.protos;

public interface EventMeshMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventmesh.common.protocol.grpc.EventMeshMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.eventmesh.common.protocol.grpc.RequestHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.eventmesh.common.protocol.grpc.RequestHeader header = 1;</code>
   */
  RequestHeader getHeader();
  /**
   * <code>.eventmesh.common.protocol.grpc.RequestHeader header = 1;</code>
   */
  RequestHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>string producerGroup = 2;</code>
   */
  String getProducerGroup();
  /**
   * <code>string producerGroup = 2;</code>
   */
  com.google.protobuf.ByteString
      getProducerGroupBytes();

  /**
   * <code>string topic = 3;</code>
   */
  String getTopic();
  /**
   * <code>string topic = 3;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string content = 4;</code>
   */
  String getContent();
  /**
   * <code>string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string ttl = 5;</code>
   */
  String getTtl();
  /**
   * <code>string ttl = 5;</code>
   */
  com.google.protobuf.ByteString
      getTtlBytes();

  /**
   * <code>string uniqueId = 6;</code>
   */
  String getUniqueId();
  /**
   * <code>string uniqueId = 6;</code>
   */
  com.google.protobuf.ByteString
      getUniqueIdBytes();

  /**
   * <code>string seqNum = 7;</code>
   */
  String getSeqNum();
  /**
   * <code>string seqNum = 7;</code>
   */
  com.google.protobuf.ByteString
      getSeqNumBytes();

  /**
   * <code>string tag = 8;</code>
   */
  String getTag();
  /**
   * <code>string tag = 8;</code>
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
