/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventmesh-client.proto

package org.apache.eventmesh.common.protocol.grpc.protos;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventmesh.common.protocol.grpc.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.eventmesh.common.protocol.grpc.RequestHeader header = 1;</code>
   */
  boolean hasHeader();
  /**
   * <code>.eventmesh.common.protocol.grpc.RequestHeader header = 1;</code>
   */
  RequestHeader getHeader();
  /**
   * <code>.eventmesh.common.protocol.grpc.RequestHeader header = 1;</code>
   */
  RequestHeaderOrBuilder getHeaderOrBuilder();

  /**
   * <code>string producerGroup = 2;</code>
   */
  String getProducerGroup();
  /**
   * <code>string producerGroup = 2;</code>
   */
  com.google.protobuf.ByteString
      getProducerGroupBytes();

  /**
   * <code>string topic = 3;</code>
   */
  String getTopic();
  /**
   * <code>string topic = 3;</code>
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string content = 4;</code>
   */
  String getContent();
  /**
   * <code>string content = 4;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string ttl = 5;</code>
   */
  String getTtl();
  /**
   * <code>string ttl = 5;</code>
   */
  com.google.protobuf.ByteString
      getTtlBytes();

  /**
   * <code>string uniqueId = 6;</code>
   */
  String getUniqueId();
  /**
   * <code>string uniqueId = 6;</code>
   */
  com.google.protobuf.ByteString
      getUniqueIdBytes();
}
