// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventmesh-client.proto

package org.apache.eventmesh.common.protocol.grpc.protos;

public interface RequestHeaderOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventmesh.common.protocol.grpc.RequestHeader)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string env = 1;</code>
   */
  String getEnv();
  /**
   * <code>string env = 1;</code>
   */
  com.google.protobuf.ByteString
      getEnvBytes();

  /**
   * <code>string region = 2;</code>
   */
  String getRegion();
  /**
   * <code>string region = 2;</code>
   */
  com.google.protobuf.ByteString
      getRegionBytes();

  /**
   * <code>string idc = 3;</code>
   */
  String getIdc();
  /**
   * <code>string idc = 3;</code>
   */
  com.google.protobuf.ByteString
      getIdcBytes();

  /**
   * <code>string ip = 4;</code>
   */
  String getIp();
  /**
   * <code>string ip = 4;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string pid = 5;</code>
   */
  String getPid();
  /**
   * <code>string pid = 5;</code>
   */
  com.google.protobuf.ByteString
      getPidBytes();

  /**
   * <code>string sys = 6;</code>
   */
  String getSys();
  /**
   * <code>string sys = 6;</code>
   */
  com.google.protobuf.ByteString
      getSysBytes();

  /**
   * <code>string username = 7;</code>
   */
  String getUsername();
  /**
   * <code>string username = 7;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string password = 8;</code>
   */
  String getPassword();
  /**
   * <code>string password = 8;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string language = 9;</code>
   */
  String getLanguage();
  /**
   * <code>string language = 9;</code>
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string protocolType = 10;</code>
   */
  String getProtocolType();
  /**
   * <code>string protocolType = 10;</code>
   */
  com.google.protobuf.ByteString
      getProtocolTypeBytes();

  /**
   * <code>string protocolVersion = 11;</code>
   */
  String getProtocolVersion();
  /**
   * <code>string protocolVersion = 11;</code>
   */
  com.google.protobuf.ByteString
      getProtocolVersionBytes();

  /**
   * <code>string protocolDesc = 12;</code>
   */
  String getProtocolDesc();
  /**
   * <code>string protocolDesc = 12;</code>
   */
  com.google.protobuf.ByteString
      getProtocolDescBytes();
}
