// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: eventmesh-client.proto

package org.apache.eventmesh.common.protocol.grpc.protos;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventmesh.common.protocol.grpc.Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string respCode = 1;</code>
   */
  String getRespCode();
  /**
   * <code>string respCode = 1;</code>
   */
  com.google.protobuf.ByteString
      getRespCodeBytes();

  /**
   * <code>string respMsg = 2;</code>
   */
  String getRespMsg();
  /**
   * <code>string respMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getRespMsgBytes();

  /**
   * <code>string respTime = 3;</code>
   */
  String getRespTime();
  /**
   * <code>string respTime = 3;</code>
   */
  com.google.protobuf.ByteString
      getRespTimeBytes();

  /**
   * <code>string seqNum = 4;</code>
   */
  String getSeqNum();
  /**
   * <code>string seqNum = 4;</code>
   */
  com.google.protobuf.ByteString
      getSeqNumBytes();
}
