// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: workflow.proto

package org.apache.eventmesh.common.protocol.workflow.protos;

@SuppressWarnings({"all"})
public interface ExecuteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:eventmesh.workflow.api.protocol.ExecuteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string instance_id = 2;</code>
   * @return The instanceId.
   */
  String getInstanceId();
  /**
   * <code>string instance_id = 2;</code>
   * @return The bytes for instanceId.
   */
  com.google.protobuf.ByteString
      getInstanceIdBytes();

  /**
   * <code>string input = 3;</code>
   * @return The input.
   */
  String getInput();
  /**
   * <code>string input = 3;</code>
   * @return The bytes for input.
   */
  com.google.protobuf.ByteString
      getInputBytes();
}
